{% set version = "1.64.0" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: boost-cpp
  version: {{ version }}

source:
  fn:  {{ filename }}
  url: https://dl.bintray.com/boostorg/release/{{ version }}/source/{{ filename }}
  sha256: 7bcc5caace97baa948931d712ea5f37038dbb1c5d89b43ad4def4ed7cb683332
  patches:
    # https://svn.boost.org/trac/boost/ticket/12516
    - boost-serialization-1.64.patch

build:
  number: 1
  features:
    - vc{{ vc }}   # [win]
  run_exports:
    # Keep boost pinned to minor version
    - {{ pin_subpackage('boost-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - icu               # [unix]
    - bzip2             # [unix]
    - zlib

  run:
    # icu removed here because package has run_exports for itself
    #    https://github.com/AnacondaRecipes/icu-feedstock/pull/1
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    # - icu 58.*          # [unix]
    # bzip2 removed here because package has run_exports for itself
    #    https://github.com/AnacondaRecipes/bzip2-feedstock/pull/2
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    # - bzip2 1.0.*       # [unix]
    # zlib removed here because zlib package has run_exports for itself
    #    https://github.com/AnacondaRecipes/zlib-feedstock/pull/2
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    # - zlib 1.2.*

test:
  commands:
    # Verify Python headers are removed.
    - "! test -f $PREFIX/include/boost/python.hpp"                      # [unix]
    - "! test -d $PREFIX/include/boost/python"                          # [unix]
    - if exist %PREFIX%\\Library\\include\\boost\\python.hpp exit 1     # [win]
    - if exist %PREFIX%\\Library\\include\\boost\\python exit 1         # [win]

    # Verify static-only libraries.
    - test -f $PREFIX/lib/libboost_exception.a                   # [unix]
    - test -f $PREFIX/lib/libboost_test_exec_monitor.a           # [unix]

    # Verify libraries.
    {% set win_vstr = "_".join(version.split(".")[:2]) %}
    {% set boost_libs = [
            "atomic",
            "chrono",
            "container",
            "context",
            "coroutine",
            "date_time",
            "filesystem",
            "graph",
            "iostreams",
            "locale",
            "log",
            "log_setup",
            "math_c99",
            "math_c99f",
            "math_c99l",
            "math_tr1",
            "math_tr1f",
            "math_tr1l",
            "prg_exec_monitor",
            "program_options",
            "random",
            "regex",
            "serialization",
            "signals",
            "system",
            "thread",
            "timer",
            "type_erasure",
            "unit_test_framework",
            "wave",
            "wserialization"
    ] %}
    {% for each_boost_lib in boost_libs %}
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.a                                                 # [unix]
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.dylib                                             # [osx]
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.so                                                # [linux]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.dll exit 1   # [win and vc==9]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.dll exit 1  # [win and vc==10]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.dll exit 1  # [win and vc==14]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.lib exit 1   # [win and vc==9]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.lib exit 1  # [win and vc==10]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.lib exit 1  # [win and vc==14]
    {% endfor %}
    - conda inspect linkages -p $PREFIX boost-cpp  # [not win]
    - conda inspect objects -p $PREFIX boost-cpp  # [osx]

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - jschueller
    - isuruf
