{% set version = "1.65.1" %}
{% set win_vstr = "1_65_1" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: libboost_multiple_outputs
  version: {{ version }}

source:
  url: https://dl.bintray.com/boostorg/release/{{ version }}/source/{{ filename }}
  sha256: 9807a5d16566c57fd74fb522764e0b134a8bbe6b6e8967b83afefd30dcd3be81
  patches:
    # https://svn.boost.org/trac10/attachment/ticket/11120/python_jam.patch
    - python_jam.patch
    # https://github.com/boostorg/build/issues/230
    - case-insensitive-env-vars.patch
    # https://github.com/boostorg/build/pull/227
    # - more-msvc-fixes.patch
    # https://github.com/boostorg/build/pull/{226,227} (a more complete version of both)
    - 0001-fix-non-c90-lines.patch
    - 0002-CONDA_BUILD-customization.patch
    - 0003-boost.python-fix-python-lib-config-dirname.patch

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - icu                   # [unix]
    - bzip2                 # [unix]
    - zlib

outputs:
  - name: libboost
    script: install-libboost.sh   # [unix]
    script: install-libboost.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - icu               # [unix]
        - bzip2             # [unix]
        - zlib
    test:
      commands:
        # Verify b2 and bjam executables work
        - b2 --help
        - bjam --help
        # Verify Python headers are removed.
        - "! test -f $PREFIX/include/boost/python.hpp"                      # [unix]
        - "! test -d $PREFIX/include/boost/python"                          # [unix]
        - if exist %PREFIX%\\Library\\include\\boost\\python.hpp exit 1     # [win]
        - if exist %PREFIX%\\Library\\include\\boost\\python exit 1         # [win]

        # Verify static-only libraries.
        - test -f $PREFIX/lib/libboost_exception.a                          # [unix]
        - test -f $PREFIX/lib/libboost_test_exec_monitor.a                  # [unix]

        # Verify libraries.
        {% set boost_libs = [
                "atomic",
                "chrono",
                "container",
                "context",
                "coroutine",
                "date_time",
                "filesystem",
                "graph",
                "iostreams",
                "locale",
                "log",
                "log_setup",
                "math_c99",
                "math_c99f",
                "math_c99l",
                "math_tr1",
                "math_tr1f",
                "math_tr1l",
                "prg_exec_monitor",
                "program_options",
                "random",
                "regex",
                "serialization",
                "signals",
                "system",
                "thread",
                "timer",
                "type_erasure",
                "unit_test_framework",
                "wave",
                "wserialization"
        ] %}
        {% for each_boost_lib in boost_libs %}
        - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.a                                                 # [unix]
        - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.dylib                                             # [osx]
        - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.so                                                # [linux]
        - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.dll exit 1   # [win and py27]
        - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.dll exit 1  # [win and py34]
        - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.dll exit 1  # [win and py35]
        - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.lib exit 1   # [win and py27]
        - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.lib exit 1  # [win and py34]
        - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.lib exit 1  # [win and py35]
        {% endfor %}
        - conda inspect linkages -p $PREFIX libboost  # [not win]
        - conda inspect objects -p $PREFIX libboost   # [osx]

  - name: py-boost
    script: install-py-boost.sh   # [unix]
    script: install-py-boost.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('libboost', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('libboost', exact=True) }}
        - python
        - numpy
    test:
      source_files: libs/python/example/*
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      commands:
        - pushd libs/python/example/tutorial
        -   bjam --debug --debug-configuration
        -   python -c 'from __future__ import print_function; import hello_ext; print(hello_ext.greet())'
        - popd

  # Metapackages to mirror conda-forge's name. It is my goal to deprecate
  # these names and eventually stop providing the packages.
  # TODO :: Aim to remove these by Oct 10th 2018.
  - name: boost-cpp
    requirements:
      run:
        - {{ pin_subpackage('libboost', exact=True) }}

  - name: boost
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('libboost', exact=True) }}
        - {{ pin_subpackage('py-boost', exact=True) }}
        - python

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - ccordoba12
    - isuruf
    - jakirkham
    - jschueller
    - mingwandroid
    - msarahan
    - ocefpaf
