travis:
  secure:
    BINSTAR_TOKEN: U9aHDlNzM2x38s/tyL8LmuOA4NMFd9AppxOYUwAX97MgadajZfcn0Q+ON0TCfB5OdvuRTYHvQUgYOo652RCh8YLjbszcWamQfOmoeNvij7WpD6+9ippCYEMXStO4+W94e8lpzbLbTxgwXET/rChJTN9tuiy8WaEwWHotIP9LqEsACTfX2ixtU/MI73tc/Epn0k2kP7KudXnd4kOswol1y20obsjE2thpKriyJNw6b6ycjHL5Af+Av+tv2ny4J5TUOLJiX6m/u2Qjdeep1Xx2mbsJyl+OT5syMRYIAiilg1FRIfP8dD336IVOM7HcUh0R5iBxjFIu6FSJAUBMnldndaiMj1vhusZbwmiGCVnSR5TnwGHiykTp1NB8/EUY4tWLIGPjA7+nG7rJt7iLVYuVodF1J2eJGNuYSEmZqbGAhLgX8omCCCi9VJSK144grRBEVFMPRrInWo5QomhKRlVfzD4vmLbsyIy7mF/KHo/TtcmksbTsxucfjXSgA8QJH6kvP8K10nFDj4qshA8yTer3NlCUFN2gQFC3N12f7hJcaVrdNW3U+NRVpuNkmI+71W1oDCgStj2Dyoa9Rm2Ln1d5HcLF1/HPYqyJc4giedkk1A0ZrrHnT5yGYx7FcFL2BJ+ZHevyAQwXScyyFqnQJSJcjdknH7SpDo531jt7qwsV+J0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
