travis:
  secure:
    BINSTAR_TOKEN: geGXAjo43aIrk/+tzCO6sruF3H4dswydbfblrfRVTGa2SxWLio7bJDJgu0KZJHen6R//p2g2YZhWEECam4uGW/cJTKMRVdtCvFY+w7rxUd3AC9W4I8Hwmy9opOeNsressx6MvokDnH19XNbFx8lZx1ox11twC9qkVOkj6H3yXXOeZ8dFMx1C/1CczQDQLnGJ5R5qbA5gmhYHhoLXT9EWXIkYvafrEsd8chLd94VzCzSDHeTWeFXQHLGyAsAxlXkMvaTHROIE0I/w9iFwdFTXy6xI00mDqXplbv2xPwFdztSr4KRIhUAutAMnmcvyRNclqEyqp/IL/nZf7vNVoFpWWWFNu/m5EkcDD6AyHbceUstmhtwguDbkSzdzSRkNYcVfu4zLVNfyRylHMVu229wJIJl9vOqNHzBrRGJ3bwmPCC2lssolO1Mu6G9R+F1z5l9lDNaRse5c5O03hgWHBbR/R6SQZdG0FX5Bw8lGMGONFNecNIm8Yv0aE57pqKdgf5Hcg3EHInKOmHyZM/IzrP8kzqcTTO9kb28sK46F20LuUXx3jlOTq4LCIs7H95rvP+frK6LtU+ob+EYR7I/xlRV74bbPKlWpMDLTcA34HpmODk2PhyJl3cntqAY+YlkG+gGxvQXWN1qewifzP/0GV7DqJ6IVnw0rVSqZgf13S7r+8Gw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
